CREATE TABLE IF NOT EXISTS ROUTES (
    routeid INT AUTO_INCREMENT PRIMARY KEY,
    route VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARS (
    carid INT AUTO_INCREMENT PRIMARY KEY,
    speed INT NOT NULL,
    routeid INT NOT NULL,
    FOREIGN KEY (routeid) REFERENCES ROUTES(routeid)
);
